[tool.poetry]
name = "fastinni"
version = "0.1.0"
description = "A simple FastAPI server"
authors = ["Khrysys <admin@khrysystem.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
asyncpg = "^0.27.0"
fastapi = {extras = ["all"], version = "^0.95.1"}
fastapi-csrf-protect = "^0.2.2"
fastapi-users = {extras = ["sqlalchemy"], version = "^10.4.2"}
python-dotenv = "^1.0.0"
sqlalchemy = "^2.0.9"
uvicorn = {extras = ["standard"], version = "^0.21.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
